# Generated by Django 3.2 on 2021-05-23 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blogg', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(verbose_name='date Published')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comm', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(verbose_name='Comment Date')),
                ('blg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.blogcontent')),
            ],
        ),
        migrations.AddField(
            model_name='blogcontent',
            name='pep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.people'),
        ),
    ]
