# Generated by Django 3.2 on 2021-05-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='commenter',
            field=models.CharField(default='Anonnymous', max_length=60),
        ),
    ]
