# Generated by Django 3.2 on 2021-05-23 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comments_commenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontent',
            name='pep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Person_obj', to='posts.people'),
        ),
    ]
