# Generated by Django 3.2 on 2021-05-23 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_blogcontent_pep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='blg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Commentss', to='posts.blogcontent'),
        ),
    ]
